# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION.
# SPDX-License-Identifier: Apache-2.0

name: pr

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: ci/check_style.sh
  test:
    runs-on: ubuntu-latest
    container:
      image: rapidsai/ci-conda:latest
    steps:
      - uses: actions/checkout@v4
      - run: ci/test.sh
